name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:    
      matrix:
        arch: [64]

    steps:
    # Install dependencies
    - name: Install libck
      run: sudo apt-get install libck-dev    
    - name: Install Cyclone
      run: |
        wget https://github.com/cyclone-scheme/binary-releases/raw/master/ubuntu-18.04-lts/cyclone-scheme_0.18_amd64.deb 
        sudo apt install ./cyclone-scheme_0.18_amd64.deb
      
    # Setup winds
    - uses: actions/checkout@v2
    - name: Build cyclone-winds
      run: make
    - name: Install cyclone-winds
      run: sudo make install
      
    # Run our tests
    - name: Run tests
      run: |
        make test
        
    # -----------------------------------------------------------------
    # Run system tasks (the order is important!)

    # Pre-requisite
    - name: Clone wiki directory
      run: |
        git clone https://github.com/cyclone-scheme/cyclone-winds.wiki.git wiki

    # Update wiki index, packages wikis and library index.
    # One command does all to avoid multiple iterations over all packages,
    # which could become too slow as the packages list grows.
    - name: Update wiki and library index
      run: |
        make sys-tasks
        make clean

    # Wiki index (already updated by 'make sys-tasks')
   - name: Push wiki changes
      # Taken from https://github.com/marketplace/actions/github-wiki-action
      uses: Andrew-Chen-Wang/github-wiki-action@v2
      env:
        # Make sure you have that / at the end. We use rsync 
        # WIKI_DIR's default is wiki/
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.AUTOMATION_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}

    - name: Clean wiki directory
      run: |
        rm -Rf wiki

    # Library index
    - name: Commit library index
      run: |
        git config --local user.email ${{ secrets.AUTOMATION_EMAIL }}
        git config --local user.name ${{ github.repository_owner }}
        git add ./indexes/library-index.scm
        [[ -z $(git status -s) ]] || git commit -m "Updated library-index.scm on push"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true


    